version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3451:3300
    restart: always

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3452:3400
    restart: always